version: '3.8'
name: bcra-mssqlserver
services:
  bcra-mssqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bcra-mssqlserver
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'Change1t2178.!'
      ACCEPT_EULA: 'Y'
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
    driver: local
